# Hit-a-Hint default preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

pref("extensions.surfkeys.enabled", true);
pref("extensions.surfkeys.resultpattern", "google.com:Next:Previous;google.fi:Seuraava:Edellinen;www.helsinginsanomat.fi/viivijawagner:SEURAAVA:EDELLINEN");
pref("extensions.surfkeys.keys", "{id: 'skScrollUp', key: 'k', alt: false, shift: false}||{id: 'skScrollDown', key: 'j', alt: false, shift: false}||{id: 'skScrollLeft', key: 'h', alt: false, shift: false}||{id: 'skScrollRight', key: 'l', alt: false, shift: false}||{id: 'skScrollPgDown', key: ';', alt: false, shift: false}||{id: 'skScrollPgUp', key: 'p', alt: false, shift: false}||{id: 'skBrowserBack', key: ',', alt: false, shift: false}||{id: 'skBrowserForward', key: '.', alt: false, shift: false}||{id: 'skBrowserStop', key: 's', alt: false, shift: false}||{id: 'skBrowserReload', key: 'r', alt: false, shift: false}||{id: 'skNext', key: 'm', alt: false, shift: false}{id: 'skPrevious', key: 'n', alt: false, shift: false}||{id: 'skTabNew', key: 't', alt: false, shift: false}||{id: 'skTabClose', key: 'y', alt: false, shift: false}||{id: 'skWinClose', key: 'w', alt: false, shift: false}||{id: 'skTabNext', key: 'o', alt: false, shift: false}||{id: 'skTabPrev', key: 'u', alt: false, shift: false}||{id: 'skGotoLocationBar', key: 'g', alt: false, shift: false}||{id: 'skMoveTabLeft', key: 'u', alt: false, shift: true}||{id: 'skMoveTabRight', key: 'o', alt: false, shift: true}||{id: 'skMoveTabBegin', key: 'b', alt: false, shift: false}||{id: 'skMoveTabEnd', key: 'e', alt: false, shift: false}||{id: 'skGoToSearch', key: 'd', alt: false, shift: false}");
