# Hit-a-Hint default preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

pref("extensions.surfkeys.enabled", true);
pref("extensions.surfkeys.disableinsidebar", false);
pref("extensions.surfkeys.lastsiteid", 0);
pref("extensions.surfkeys.resultpattern", "google.com:Next:Previous;google.fi:Seuraava:Edellinen;www.helsinginsanomat.fi/viivijawagner:SEURAAVA:EDELLINEN");
pref("extensions.surfkeys.keys","{skScrollUp:{key:'k',alt:false,shift:false,disabled:false},skScrollDown:{key:'j',alt:false,shift:false,disabled:false},skScrollLeft:{key:'h',alt:false,shift:false,disabled:false},skScrollRight:{key:'l',alt:false,shift:false,disabled:false},skScrollPgDown:{key:';',alt:false,shift:false,disabled:false},skScrollPgUp:{key:'p',alt:false,shift:false,disabled:false},skBrowserBack:{key:',',alt:false,shift:false,disabled:false},skBrowserForward:{key:'.',alt:false,shift:false,disabled:false},skBrowserStop:{key:'s',alt:false,shift:false,disabled:false},skBrowserReload:{key:'r',alt:false,shift:false,disabled:false},skNext:{key:'m',alt:false,shift:false,disabled:false},skPrevious:{key:'n',alt:false,shift:false,disabled:false},skTabNew:{key:'t',alt:false,shift:false,disabled:false},skTabClose:{key:'y',alt:false,shift:false,disabled:false},skWinClose:{key:'w',alt:false,shift:false,disabled:false},skTabNext:{key:'o',alt:false,shift:false,disabled:false},skTabPrev:{key:'u',alt:false,shift:false,disabled:false},skGotoLocationBar:{key:'g',alt:false,shift:false,disabled:false},skMoveTabLeft:{key:'u',alt:false,shift:true,disabled:false},skMoveTabRight:{key:'o',alt:false,shift:true,disabled:false},skMoveTabBegin:{key:'b',alt:false,shift:false,disabled:false},skMoveTabEnd:{key:'e',alt:false,shift:false,disabled:false},skGoToSearch:{key:'d',alt:false,shift:false,disabled:false},skFocusFirst:{key:'f',alt:false,shift:false,disabled:false},skFocusLast:{key:'v',alt:false,shift:false,disabled:false},skUp:{key:'c',alt:false,shift:false,disabled:false}}");
