# Hit-a-Hint default preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

pref("extensions.surfkeys.enabled", true);
pref("extensions.surfkeys.resultpattern", "google.com:Next:Previous;google.fi:Seuraava:Edellinen;www.helsinginsanomat.fi/viivijawagner:SEURAAVA:EDELLINEN");
pref("extensions.surfkeys.keys", "{ skScrollUp: {key: 'k', alt: false, shift: false}, skScrollDown: {key: 'j', alt: false, shift: false}, skScrollLeft: {key: 'h', alt: false, shift: false}, skScrollRight: {key: 'l', alt: false, shift: false}, skScrollPgDown: {key: ';', alt: false, shift: false}, skScrollPgUp: {key: 'p', alt: false, shift: false}, skBrowserBack: {key: ',', alt: false, shift: false}, skBrowserForward: {key: '.', alt: false, shift: false}, skBrowserStop: {key: 's', alt: false, shift: false}, skBrowserReload: {key: 'r', alt: false, shift: false}, skNext: {key: 'm', alt: false, shift: false}, skPrevious: {key: 'n', alt: false, shift: false}, skTabNew: {key: 't', alt: false, shift: false}, skTabClose: {key: 'y', alt: false, shift: false}, skWinClose: {key: 'w', alt: false, shift: false}, skTabNext: {key: 'o', alt: false, shift: false}, skTabPrev: {key: 'u', alt: false, shift: false}, skGotoLocationBar: {key: 'g', alt: false, shift: false}, skMoveTabLeft: {key: 'u', alt: false, shift: true}, skMoveTabRight: {key: 'o', alt: false, shift: true}, skMoveTabBegin: {key: 'b', alt: false, shift: false}, skMoveTabEnd: {key: 'e', alt: false, shift: false}, skGoToSearch: {key: 'd', alt: false, shift: false} }");
